apiVersion: v1
kind: Service
metadata:
  name: research-ui
spec:
  type: LoadBalancer # NodePort for Minikube local access usually, but LB works with minikube tunnel
  selector:
    app: research-ui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
